name: Daily Job

on:
  schedule:
    - cron: "*/5 * * * *" # Runs daily at midnight UTC
  workflow_dispatch: 

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: node index.js
